[package]
name = "bintrade_egui"
version = "0.1.0"
edition = "2024"
authors = ["DB <dd555@protonmail.com>"]
description = "GUI binance trade program using egui. Do live trading, historic data and simulate trading, plot historic data"
license= "MIT"
include =["/src","LICENSE.md", "Settings.toml", "Cargo.toml"]
exclude =["Cargo.lock"]

[profile.release]
strip=true 
lto = true 
opt-level = 2 
codegen-units = 1 

[features]
default=["yfinance"]
yfinance=["dep:yahoo_finance_api", "dep:yfinance-rs"]

[dependencies]
yahoo_finance_api ={ version="4.1.0", optional=true}
yfinance-rs = { version="0.1.3", optional=true}

anyhow = "1.0.98"
binance-async = "0.3.0"
chrono = "0.4.41"
config = "0.15.13"
eframe = { version = "0.32", default-features = false, features = ["accesskit", "default_fonts", "glow", "persistence", "wayland", "x11"] }
egui = { version = "0.32.0", features = ["persistence", "serde"] }
winit = {version="0.30.12", default-features = false,features = ["wayland"] }
egui_extras = { version = "0.32.0", features = ["datepicker", "image", "serde"] }
egui_plot_bintrade = "0.33.1"
egui_tiles = "0.13.0"
futures = "0.3.31"
log = { version = "0.4.27"}
plotters = "0.3.7"
rust_decimal = "1.37.2"
serde = "1.0.219"
serde_derive = "1.0.219"
serde_json = "1.0.142"
sqlx = { version = "0.8.6", features = ["runtime-tokio-native-tls", "sqlite", "chrono"] }
strum = "0.27.2"
strum_macros = "0.27.2"
tokio = { version = "1.47.0", features = ["full"] }
websockets = "0.3.0"
tokio-util = "0.7.16"
time = "0.3.44"
binance = "0.21.2"
bincode = "2.0.1"
tracing = "0.1.41"
color-backtrace = "0.7.1"
env_logger = "0.11.8"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
derive-debug = "0.1.2"
num = "0.4.3"
reqwest = { version = "0.13.1", features = ["json", "multipart"] }
linya = "0.3.1"
<<<<<<< HEAD
magic-crypt = "4.0.1"
=======
>>>>>>> master
