#Binance credentials
api_key= "<your api key>"
api_secret= "<your secret api key>"

##Chart config
default_symbol="BTCUSDT"
default_interval="15min"
next_wicks=25

k0_inc=0.005
k1_inc=0.1
k2_inc=0.1

####Historic trade defaults
h_fee=0.0015
h_chart_type=0
h_start_money=10000
